# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.TextField(max_length=254)),
                ('Patient_History', models.TextField()),
                ('Credential', models.FileField(upload_to=doctor.models.get_upload_file_name)),
            ],
        ),
    ]
