# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 21:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Doctor_Visited_Id',
            field=models.TextField(default=datetime.datetime(2016, 3, 9, 21, 32, 18, 236314, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
