# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_patient_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='UserID',
        ),
    ]
