# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_patient_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDevicesForPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.TextField(max_length=254)),
                ('SugarMonitoringDevice', models.BooleanField(default=True)),
                ('WorkOutMachineDevice', models.BooleanField(default=True)),
                ('PulseMonitor', models.BooleanField(default=True)),
                ('TemperatureMonitor', models.BooleanField(default=True)),
                ('SleepPatternsMonitor', models.BooleanField(default=True)),
                ('GulcoseMonitoringDeviceID', models.CharField(max_length=200)),
                ('WorkOutMachineDeviceID', models.CharField(max_length=200)),
                ('PulseMonitorID', models.CharField(max_length=200)),
                ('TemperatureMonitorID', models.CharField(max_length=200)),
                ('SleepPatternsDeviceID', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='FullAddress',
            field=models.TextField(default='Full Address', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='FullName',
            field=models.CharField(default='Full Name', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='RegisterPatientRemoteMonitoring',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
