# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20160825_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdevicesforpatient',
            name='Patient_ID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient'),
        ),
    ]
