# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20160825_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InsuranceCompanyName', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='InsuranceCompanyID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.InsuranceCompany'),
        ),
    ]
