# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20160825_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataOfReading', models.DateTimeField(auto_now_add=True)),
                ('SugarMonitoringDeviceReading', models.FloatField(default=0)),
                ('WorkOutMachineDeviceReading', models.FloatField(default=0)),
                ('PulseMonitorReading', models.FloatField(default=0)),
                ('TemperatureMonitorReading', models.FloatField(default=0)),
                ('SleepPatternsMonitorReading', models.FloatField(default=0)),
                ('InsuranceCompanyID', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.InsuranceCompany')),
                ('Patient_ID', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='doctor.Patient')),
            ],
        ),
    ]
